---
# Contains the configuration for base nfs kit.
instance_groups:
- name: nfsbroker
  instances: 1
  azs: (( grab params.availability_zones ))
  persistent_disk_pool: (( grab params.disk_pool ))
  vm_type: (( grab params.vm_type ))
  stemcell: default
  networks:
  - name: (( grab params.network ))
    static_ips: (( static_ips(0) ))
  jobs:
  - name: nfsbroker
    release: nfs-volume
    properties:
      nfsbroker:
        plan_desc: broker for exisiting NFS shares
        username: nfs-broker
        password: (( vault meta.vault "broker:password" ))
  - name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: (( grab params.cf_deployment ))
    properties:
      route_registrar:
        routes:
          - name: nfs-broker
            port: 8999
            registration_interval: 20s
            tags:
              component: nfs-broker
            uris:
              - (( concat "nfs-broker." params.system_domain ))
- name: nfs-broker-registrar
  instances: 1
  lifecycle: errand
  azs: (( grab params.availability_zones ))
  vm_type: (( grab params.vm_type ))
  stemcell: default
  networks:
  - name: (( grab params.network ))
  jobs:
  - name: broker-registrar
    release: broker-registrar
    properties:
      servicebroker:
        url: (( concat "http://nfs-broker." params.system_domain ))
        name: nfs-broker
        username: nfs-broker
        password: ((vault meta.vault "broker:password" ))
      cf:
        api_url: (( concat "api." params.system_domain ))
        username: (( grab params.cf_admin_user ))
        password: (( vault params.cf_admin_pass ))
        skip_ssl_validation: (( grab params.skip_ssl_validation ))

releases:
- name: nfs-volume
  version: 1.0.4
  sha1: b2c22394d30c212a9e6dfcdd0abf5879e931ebfe
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/nfs-volume-release?v=1.0.4
- name: broker-registrar
  version: 3.2.2
  url: https://bosh.io/d/github.com/cloudfoundry-community/broker-registrar-boshrelease?v=3.2.2
  sha1: f82c6a346d871ccb9835b8e6341f966cf7ebc7c9
- name: routing
  version: 0.156.0
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.156.0
  sha1: c0cbf0a4851a36e16a3d8c8cd735d9f64fc4c702

stemcells:
- alias: default
  os: (( grab params.stemcell_os ))
  version: (( grab params.stemcell_version ))

update:
  serial: false
  canaries: 1
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  max_in_flight: 1
  max_errors: 1
