---
# Contains the configuration for base nfs kit.
instance_groups:
- name: nfsbroker
  instances: 1
  azs: (( grab params.availability_zones ))
  persistent_disk_pool: (( grab params.disk_pool ))
  vm_type: (( grab params.vm_type ))
  stemcell: default
  networks:
  - name: (( grab params.network ))
  jobs:
  - name: nfsbroker
    release: nfs-volume
    properties:
      nfsbroker:
        plan_desc: broker for exisiting NFS shares
        username: nfs-broker
        password: (( vault meta.vault "broker:password" ))
  - name: route_registrar
    release: routing
    consumes:
      nats:
        from: nats
        deployment: (( grab params.cf_deployment ))
    properties:
      route_registrar:
        routes:
          - name: nfs-broker
            port: 8999
            registration_interval: 20s
            tags:
              component: nfs-broker
            uris:
              - (( concat "nfs-broker." params.system_domain ))
- name: nfs-broker-registrar
  instances: 1
  lifecycle: errand
  azs: (( grab params.availability_zones ))
  vm_type: (( grab params.vm_type ))
  stemcell: default
  networks:
  - name: (( grab params.network ))
  jobs:
  - name: broker-registrar
    release: broker-registrar
    properties:
      servicebroker:
        url: (( concat "http://nfs-broker." params.system_domain ))
        name: nfs-broker
        username: nfs-broker
        password: ((vault meta.vault "broker:password" ))
      cf:
        api_url: (( concat "api." params.system_domain ))
        username: (( grab params.cf_admin_user ))
        password: (( vault params.cf_admin_pass ))
        skip_ssl_validation: (( grab params.skip_ssl_validation ))

releases:
- name: nfs-volume
  version: 1.0.7
  sha1: f609a25be32e1fc634e683cc3a89c0aaad1e70f0
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/nfs-volume-release?v=1.0.7
- name: broker-registrar
  version: 3.3.1
  url: https://bosh.io/d/github.com/cloudfoundry-community/broker-registrar-boshrelease?v=3.3.1
  sha1: 3625828feca7134fd895adf0470bfd91b628bc22
- name: routing
  version: 0.162.0
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.162.0
  sha1: f17cf09d2414f5f486d18bbd57b17fd48fb69773

stemcells:
- alias: default
  os: (( grab params.stemcell_os ))
  version: (( grab params.stemcell_version ))

update:
  serial: false
  canaries: 1
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  max_in_flight: 1
  max_errors: 1
