---
meta:
  vault: (( concat "secret/" params.vault "/" ))

params:
  system_domain: (( param "What is the system domain of the Cloud Foundry NFS broker should register with?" ))
  cf_admin_user: admin
  cf_admin_pass: (( param "What is the vault path to the CF admin user that NFS broker should register with?" ))
  skip_ssl_validation: false

  cf_deployment: (( concat params.env "-cf" ))

  availability_zones:
  - z1

  vm_type: small
  disk_pool: small
  network: default

  stemcell_os: ubuntu-trusty
  stemcell_version: latest
